INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (1,'Clínica São Lucas','PRIVADO',1);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (2,'Hospital Santa Maria','PUBLICO',2);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (3,'Centro Médico Vida Nova','PRIVADO',3);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (4,'Ambulatório São José','PUBLICO',4);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (5,'Unidade de Saúde Esperança','PRIVADO',5);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (6,'Centro de Atendimento Médico Integrado','PUBLICO',6);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (7,'Clínica Popular Bem Estar','PRIVADO',7);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (8,'Hospital Municipal Nossa Senhora da Paz','PUBLICO',8);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (9,'Centro Médico da Família','PRIVADO',9);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (10,'Unidade de Saúde Cuidar','PUBLICO',10);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (11,'Hospital Regional São João','PRIVADO',11);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (12,'Clínica Saúde Total','PUBLICO',12);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (13,'Centro de Atendimento Médico Especializado','PRIVADO',13);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (14,'Ambulatório Esperança Viva','PUBLICO',14);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (15,'Hospital São Francisco de Assis','PRIVADO',15);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (16,'Hospital São Francisco de Assis','PUBLICO',16);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (17,'Unidade de Saúde Bem Estar','PRIVADO',17);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (18,'Centro Médico Esperança Nova','PUBLICO',18);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (19,'Clínica Popular Saúde em Dia','PRIVADO',19);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (20,'Hospital Municipal São Pedro','PUBLICO',20);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (21,'Unidade de Saúde Mais Saúde','PRIVADO',21);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (22,'Hospital Regional São Lucas','PUBLICO',22);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (23,'Clínica Saúde Total','PRIVADO',23);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (24,'Centro de Atendimento Médico Integrado','PUBLICO',24);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (25,'Ambulatório Bem Estar Viva','PRIVADO',25);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (26,'Unidade de Saúde São João','PUBLICO',26);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (27,'Centro Médico Cuidar Bem','PRIVADO',27);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (28,'Clínica Popular Vida Nova','PUBLICO',28);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (29,'Hospital Municipal Nossa Senhora da Paz','PRIVADO',29);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (30,'Centro de Saúde da Família','PUBLICO',30);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (31,'Unidade de Saúde Esperança Viva','PRIVADO',31);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (32,'Hospital São Francisco de Assis','PUBLICO',32);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (33,'Clínica Saúde Total','PRIVADO',33);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (34,'Centro Médico da Família','PUBLICO',34);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (35,'Ambulatório São José','PRIVADO',35);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (36,'Unidade de Saúde Mais Saúde','PUBLICO',36);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (37,'Centro de Atendimento Médico Integrado','PRIVADO',37);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (38,'Hospital Regional São João','PUBLICO',38);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (39,'Clínica Popular Saúde em Dia','PRIVADO',39);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (40,'Centro Médico Esperança Nova','PUBLICO',40);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (41,'Unidade de Saúde Cuidar','PRIVADO',41);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (42,'Hospital Municipal São Pedro','PUBLICO',42);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (43,'Centro de Saúde da Família','PRIVADO',43);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (44,'Clínica Saúde Total','PUBLICO',44);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (45,'Centro Médico Cuidar Bem','PRIVADO',45);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (46,'Ambulatório Bem Estar Viva','PUBLICO',46);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (47,'Unidade de Saúde São João','PRIVADO',47);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (48,'Hospital Regional São Lucas','PUBLICO',48);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (49,'Centro de Atendimento Médico Especializado','PRIVADO',49);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (50,'Clínica Popular Vida Nova','PUBLICO',50);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (51,'Hospital Municipal Nossa Senhora da Paz','PRIVADO',51);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (52,'Unidade de Saúde Esperança Viva','PUBLICO',52);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (53,'Hospital São Francisco de Assis','PRIVADO',53);
INSERT INTO centro (`id_centro`,`nome`,`tipo`,`fk_id_endereco_centro`) VALUES (54,'Hospital Santa Genoveva','PUBLICO',54);
