INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (1,'AC','Rio Branco','Centro','69900000','Rua Acre','Prédio 1');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (2,'AC','Rio Branco','Bosque','69901000','Avenida Amazônia','Apartamento 101');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (3,'AC','Rio Branco','Floresta','69902000','Travessa dos Ipês','Casa 5');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (4,'AL','Maceió','Ponta Verde','57000000','Rua da Praia','Apartamento 501');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (5,'AL','Maceió','Farol','57001000','Avenida Fernandes Lima','Loja 10');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (6,'AL','Maceió','Pajuçara','57002000','Rua Senador Mendonça','Sobrado 2');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (7,'AM','Manaus','Centro','69000000','Avenida Eduardo Ribeiro','Loja 1');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (8,'AM','Manaus','Adrianópolis','69001000','Rua Salvador','Sala 202');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (9,'AM','Manaus','Parque Dez','69002000','Avenida das Torres','Apartamento 301');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (10,'AP','Macapá','Central','68900000','Rua do Canal','Casa 1');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (11,'AP','Macapá','Santa Rita','68901000','Avenida FAB','Apartamento 102');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (12,'AP','Macapá','Buritizal','68902000','Travessa das Flores','Casa 8');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (13,'BA','Salvador','Centro','40000000','Avenida Sete de Setembro','Loja 2');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (14,'BA','Salvador','Itaigara','40001000','Rua das Acácias','Sala 203');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (15,'BA','Salvador','Pituba','40002000','Avenida Manoel Dias','Apartamento 402');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (16,'CE','Fortaleza','Centro','60000000','Avenida Dom Manuel','Loja 3');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (17,'CE','Fortaleza','Aldeota','60001000','Rua Torres Câmara','Sala 204');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (18,'CE','Fortaleza','Meireles','60002000','Avenida Beira Mar','Apartamento 503');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (19,'DF','Brasília','Asa Sul','70000000','SQS 102','Apartamento 201');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (20,'DF','Brasília','Asa Norte','70001000','SCLRN 304','Loja 5');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (21,'DF','Brasília','Lago Sul','70002000','SHIS QI 9','Casa 15');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (22,'ES','Vitória','Centro','29000000','Avenida Jerônimo Monteiro','Loja 6');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (23,'ES','Vitória','Jardim da Penha','29001000','Rua Belmiro Rodrigues da Silva','Sala 205');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (24,'ES','Vitória','Praia do Canto','29002000','Avenida Rio Branco','Apartamento 601');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (25,'GO','Goiânia','Setor Central','70000000','Avenida Anhanguera','Loja 7');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (26,'GO','Goiânia','Setor Bueno','70001000','Rua T10','Sala 206');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (27,'GO','Goiânia','Setor Oeste','70002000','Avenida Assis Chateaubriand','Apartamento 701');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (28,'MA','São Luís','Centro','65000000','Rua Grande','Loja 8');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (29,'MA','São Luís','Cohama','65001000','Avenida Daniel de La Touche','Sala 207');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (30,'MA','São Luís','Calhau','65002000','Avenida dos Holandeses','Apartamento 801');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (31,'MT','Cuiabá','Centro Norte','78000000','Avenida Isaac Póvoas','Loja 9');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (32,'MT','Cuiabá','Bosque da Saúde','78001000','Rua São Sebastião','Sala 208');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (33,'MT','Cuiabá','Jardim das Américas','78002000','Avenida das Flores','Apartamento 901');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (34,'MS','Campo Grande','Centro','79000000','Avenida Afonso Pena','Loja 10');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (35,'MS','Campo Grande','Jardim dos Estados','79001000','Rua Antônio Maria Coelho','Sala 209');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (36,'MS','Campo Grande','Bairro Tiradentes','79002000','Avenida Bandeirantes','Apartamento 1002');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (37,'MG','Belo Horizonte','Centro','30000000','Avenida Afonso Pena','Loja 11');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (38,'MG','Belo Horizonte','Savassi','30001000','Rua Pernambuco','Sala 210');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (39,'MG','Belo Horizonte','Lourdes','30002000','Avenida Bias Fortes','Apartamento 1102');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (40,'PA','Belém','Batista Campos','66000000','Travessa Padre Eutíquio','Loja 12');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (41,'PA','Belém','Nazaré','66001000','Avenida Almirante Barroso','Sala 211');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (42,'PA','Belém','Umarizal','66002000','Rua dos Pariquis','Apartamento 1203');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (43,'PB','João Pessoa','Centro','58000000','Avenida Epitácio Pessoa','Loja 13');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (44,'PB','João Pessoa','Manaíra','58001000','Rua Maria Caetano Fernandes de Lima','Sala 212');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (45,'PB','João Pessoa','Tambaú','58002000','Avenida Presidente Epitácio Pessoa','Apartamento 1304');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (46,'PR','Curitiba','Centro','80000000','Rua XV de Novembro','Loja 14');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (47,'PR','Curitiba','Batel','80001000','Alameda Dr. Carlos de Carvalho','Sala 213');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (48,'PR','Curitiba','Água Verde','80002000','Avenida República Argentina','Apartamento 1405');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (49,'PE','Recife','Boa Viagem','50000000','Avenida Boa Viagem','Loja 15');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (50,'PE','Recife','Graças','50001000','Rua Joaquim Nabuco','Sala 214');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (51,'PE','Recife','Pina','50002000','Avenida Herculano Bandeira','Apartamento 1506');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (52,'PI','Teresina','Centro','64000000','Avenida Frei Serafim','Loja 16');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (53,'PI','Teresina','Jóquei','64001000','Rua Goiás','Sala 215');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (54,'PI','Teresina','Ininga','64002000','Avenida Nossa Senhora de Fátima','Apartamento 1607');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (55,'RJ','Rio de Janeiro','Centro','20000000','Rua do Rosário','Loja 17');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (56,'RJ','Rio de Janeiro','Copacabana','20001000','Avenida Nossa Senhora de Copacabana','Sala 216');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (57,'RJ','Rio de Janeiro','Ipanema','20002000','Rua Visconde de Pirajá','Apartamento 1708');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (58,'RN','Natal','Centro','59000000','Avenida Rio Branco','Loja 18');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (59,'RN','Natal','Ponta Negra','59001000','Rua Erivan França','Sala 217');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (60,'RN','Natal','Tirol','59002000','Avenida Hermes da Fonseca','Apartamento 1809');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (61,'RS','Porto Alegre','Centro','90000000','Avenida Borges de Medeiros','Loja 19');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (62,'RS','Porto Alegre','Moinhos de Vento','90001000','Rua Padre Chagas','Sala 218');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (63,'RS','Porto Alegre','Belém Novo','90002000','Avenida Juca Batista','Apartamento 1909');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (64,'RO','Porto Velho','Centro','76800000','Avenida Sete de Setembro','Loja 20');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (65,'RO','Porto Velho','Caiari','76801000','Rua Dom Pedro II','Sala 219');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (66,'RO','Porto Velho','Olaria','76802000','Avenida Calama','Apartamento 2009');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (67,'RR','Boa Vista','Centro','69300000','Avenida Ville Roy','Loja 21');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (68,'RR','Boa Vista','São Francisco','69301000','Rua Agnelo Bittencourt','Sala 220');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (69,'RR','Boa Vista','Liberdade','69302000','Avenida Brigadeiro Eduardo Gomes','Apartamento 2102');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (70,'SC','Florianópolis','Centro','88000000','Rua Felipe Schmidt','Loja 22');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (71,'SC','Florianópolis','Trindade','88001000','Avenida Madre Benvenuta','Sala 221');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (72,'SC','Florianópolis','Itacorubi','88002000','Rua Lauro Linhares','Apartamento 2202');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (73,'SP','São Paulo','Centro','01000000','Rua Direita','Loja 23');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (74,'SP','São Paulo','Jardins','01001000','Alameda Santos','Sala 222');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (75,'SP','São Paulo','Moema','01002000','Avenida Bemtevi','Apartamento 2302');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (76,'SE','Aracaju','Centro','49000000','Rua João Pessoa','Loja 24');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (77,'SE','Aracaju','Atalaia','49001000','Avenida Santos Dumont','Sala 223');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (78,'SE','Aracaju','Grageru','49002000','Rua Laranjeiras','Apartamento 2403');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (79,'TO','Palmas','Centro','77000000','Avenida JK','Loja 25');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (80,'TO','Palmas','Plano Diretor Norte','77001000','Quadra 104 Norte','Sala 224');
INSERT INTO endereco_pessoa (`id_endereco_pessoa`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (81,'TO','Palmas','Plano Diretor Sul','77002000','Quadra 204 Sul','Apartamento 2504');
