INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (1,'AC','Rio Branco','Estação Experimental','69903000','Alameda das Flores','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (2,'AC','Rio Branco','Cadeia Velha','69904000','Praça da Liberdade','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (3,'AL','Maceió','Jatiúca','57003000','Avenida Álvaro Otacílio','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (4,'AL','Maceió','Centro','57004000','Rua do Comércio','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (5,'AM','Manaus','Compensa','69003000','Travessa do Sol','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (6,'AM','Manaus','Cidade Nova','69004000','Avenida Noel Nutels','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (7,'AP','Macapá','Congós','68903000','Alameda dos Ipês','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (8,'AP','Macapá','Pacoval','68904000','Praça da Independência','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (9,'BA','Salvador','Barra','40003000','Travessa da Barra','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (10,'BA','Salvador','Stiep','40004000','Avenida Tancredo Neves','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (11,'CE','Fortaleza','Mucuripe','60003000','Travessa dos Navegantes','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (12,'CE','Fortaleza','Cocó','60004000','Avenida Engenheiro Santana Júnior','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (13,'DF','Brasília','Lago Norte','70003000','SHIN QL 10','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (14,'DF','Brasília','Sudoeste','70004000','CLSW 300A','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (15,'ES','Vitória','Jardim Camburi','29003000','Rua Aleixo Netto','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (16,'ES','Vitória','Enseada do Suá','29004000','Avenida Nossa Senhora dos Navegantes','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (17,'GO','Goiânia','Setor Campinas','70003000','Rua 24 de Outubro','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (18,'GO','Goiânia','Setor Marista','70004000','Avenida Ricardo Paranhos','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (19,'MA','São Luís','Renascença','65003000','Rua dos Maçaricos','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (20,'MA','São Luís','Turu','65004000','Avenida dos Africanos','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (21,'MT','Cuiabá','Santa Rosa','78003000','Rua dos Ipês','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (22,'MT','Cuiabá','Quilombo','78004000','Avenida Historiador Rubens de Mendonça','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (23,'MS','Campo Grande','Jardim Aeroporto','79003000','Rua da Paz','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (24,'MS','Campo Grande','Amambaí','79004000','Avenida Ernesto Geisel','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (25,'MG','Belo Horizonte','Funcionários','30003000','Rua Gonçalves Dias','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (26,'MG','Belo Horizonte','Barro Preto','30004000','Avenida Augusto de Lima','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (27,'PA','Belém','Cremação','66003000','Travessa Apinagés','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (28,'PA','Belém','Marco','66004000','Avenida Pedro Miranda','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (29,'PB','João Pessoa','Bessa','58003000','Rua Francisco Leocádio Ribeiro Coutinho','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (30,'PB','João Pessoa','Cabo Branco','58004000','Avenida Olinda','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (31,'PR','Curitiba','Champagnat','80003000','Rua Padre Anchieta','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (32,'PR','Curitiba','Ecoville','80004000','Rua Monsenhor Ivo Zanlorenzi','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (33,'PE','Recife','Madalena','50003000','Rua Real da Torre','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (34,'PE','Recife','Espinheiro','50004000','Avenida Agamenon Magalhães','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (35,'PI','Teresina','Dirceu','64003000','Rua das Orquídeas','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (36,'PI','Teresina','Satélite','64004000','Avenida Zequinha Freire','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (37,'RJ','Rio de Janeiro','Botafogo','20003000','Rua Voluntários da Pátria','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (38,'RJ','Rio de Janeiro','Barra da Tijuca','20004000','Avenida das Américas','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (39,'RN','Natal','Lagoa Nova','59003000','Rua São José','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (40,'RN','Natal','Candelária','59004000','Avenida Prudente de Morais','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (41,'RS','Porto Alegre','Cristal','90003000','Rua Diário de Notícias','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (42,'RS','Porto Alegre','Petrópolis','90004000','Avenida Protásio Alves','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (43,'RO','Porto Velho','Embratel','76803000','Rua Alexandre Guimarães','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (44,'RO','Porto Velho','Nova Porto Velho','76804000','Avenida Rio de Janeiro','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (45,'RR','Boa Vista','Caranã','69303000','Rua das Três Marias','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (46,'RR','Boa Vista','Jóquei Clube','69304000','Avenida dos Imigrantes','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (47,'SC','Florianópolis','Coqueiros','88003000','Avenida Engenheiro Max de Souza','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (48,'SC','Florianópolis','Saco Grande','88004000','Rua Deputado Antônio Edu Vieira','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (49,'SP','São Paulo','Pinheiros','01003000','Rua dos Pinheiros','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (50,'SP','São Paulo','Vila Olímpia','01004000','Avenida Brigadeiro Faria Lima','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (51,'SE','Aracaju','São Conrado','49003000','Avenida Desembargador Maynard','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (52,'SE','Aracaju','Coroa do Meio','49004000','Avenida Beira Mar','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (53,'TO','Palmas','Taquaralto','77003000','Avenida Tocantins','');
INSERT INTO endereco_centro (`id_endereco_centro`,`estado`,`cidade`,`bairro`,`cep`,`logradouro`,`complemento`) VALUES (54,'TO','Palmas','Jardim Aureny III','77004000','Rua 7','');
